### PR TITLE
some more python links

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by ches** [comment]
So I was using [the repo wiki](https://github.com/bkkhack/resources/wiki) for language-specific stuff, thinking it's more manageable than one big document and less friction for small edits that probably won't cause much debate. Pull requests have some possible nice aspects for this but maybe negative ones too, I'm still open to thoughts on which way to go… /cc @jean

**Comment by jean** [comment]
There's this emerging trend of "awesome" repos that consist of basically one honking big document: 
https://github.com/kahun/awesome-sysadmin
https://github.com/ziadoz/awesome-php
https://github.com/caesar0301/awesome-public-datasets
https://github.com/qinwf/awesome-R
https://github.com/bayandin/awesome-awesomeness
and last but not least https://github.com/vinta/awesome-python .. 
I'm fine either way ..

**Comment by djay** [comment]
I’m confused. Why have two pages. Can’t we have the front page as a wiki?

**Comment by jean** [comment]
@djay the distinction is between the README of the repo and the wiki. 
The README of the repo is not a wiki (though it can also be edited through the web).
The main difference is that the wiki makes it easier to split into many pages and crosslink (this also makes it easier make a mess of half-finished pages and broken links).

**Comment by ches** [comment]
Closing in favor of [the wiki](https://github.com/bkkhack/resources/wiki/Python), per c864d393fd6.

**Pull request closed without merging**
